name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Install dependencies
      run: msbuild /t:Restore /p:Configuration=Release src/macropse.sln
    - name: Build
      run: msbuild /p:Configuration=Release src/macropse.csproj
